name: stylua
on:
  push: {branches: ["master"]}

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

    - uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        args: --config-path=stylua.toml lua/

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "style(format): run stylua"
        branch: ${{ github.head_ref }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
