- name: Checkout
  uses: actions/checkout@v3
  with:
    path: main
    token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

- name: Checkout private tools
  uses: actions/checkout@v3
  with:
    repository: my-org/my-private-tools
    token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
    path: my-tools
- uses: actions/checkout@v3
  with:
    ref: ${{ github.event.pull_request.head.sha }}
